import { NextRequest } from 'next/server';
import { addEvent } from './model';
import getEvents from './model/getEvents';
import sendEmail from '../email/sendEmail';

export async function GET(req: NextRequest) {
    try {
        const date = await req.nextUrl.searchParams?.get('date');
        if (date) {
            const data = await getEvents(date);
            return new Response(JSON.stringify(data));
        }
        throw new Error('Date not defined!');
    } catch (e: any) {
        return new Response(null, { status: 401, statusText: e.message  });
    }
}

export async function POST(req: Request) {
    try {
        const formData = await req?.formData();
        if (!formData) {
            throw new Error('Missing payload!');
        }
        let payload: any = {};
        formData.forEach((v, k) => payload[k] = v);
        const calRes = await addEvent(payload as any);
        let emailHTML = `<html lang="en">
        <body>
            <h3><b>You have created the following event with ${process.env.NEXT_PUBLIC_GOOGLE_CALENDAR_ID}</b></h3>
            <ul>
                <li>
                    <strong>Name:</strong>
                    <span>${payload.eventName}</span>
                </li>
                <li>
                    <div>
                        <strong>Start:</strong>
                        <span>${payload.startDate}</span>
                    </div>
                </li>
                <li>
                    <div>
                        <strong>End:</strong>
                        <span>${payload.endDate}</span>
                    </div>
                </li>
                ${payload.description ? `<li>
                    <div>
                        <strong>Description:</strong>
                        <span>${payload.description}</span>
                    </div>
                </li>` : ''}
                ${payload.location ? `<li>
                    <div>
                        <strong>Location:</strong>
                        <span>${payload.location}</span>
                    </div>
                </li>` : ''}
            </ul>
            <h5><b>> This is an autogenerated email, please do NOT reply.</b></h5>
        </body>
    </html>`;
        emailHTML = emailHTML.replaceAll('\n', '');
        const emailRes = await sendEmail('Acknowledgement of event creation', emailHTML);

        return new Response(JSON.stringify({
            addCalendarResponse: calRes,
            sendEmailResponse: emailRes
        }), { status: 201 });
    } catch (e: any) {
        return new Response(null, { status: 401, statusText: e.message  });
    }
}